### ISSUE TITLE
🚀 [feature] 티켓 qr코드 페이지 컴포넌트

### ISSUE THREAD

**Issue by 9yujin** [Gosrock/Ticket-Front-22nd#14]
# 🤖 기능 개요

큐알코드 페이지 관련 컴포넌트, 스토리 제작
### ✅ Implement TODO

- [x] 큐알코드 라이브러리,
- [x] 티켓 상태마다 스타일링
- [x] 소켓 세팅

**Comment by ImNM** [comment]
소켓은 백엔드 우리 위키에 엔드포인트랑
설명있음!! @9yujin
