### ISSUE TITLE
[QA] 이슈 모음

### ISSUE THREAD

**Issue by 9yujin** [Gosrock/Ticket-Front-22nd#48]
# 🤖 기능 개요

QA 중 발견된 이슈에 대해서 남깁니다.
코멘트로 쭉쭉 달아주세요.

대응 중 : 👀
대응 완료 : 🚀
확인 완료 : 👍 

꼭 👀 이모지 다신 후에 작업 시작해주세요. 대응 완료 후엔 🚀 추가로 달아주심 됩니다.

**Comment by ImNM** [comment]
화면 : 티켓 하나 페이지
url : tickets/{ticketId}
오류 내용
잘못된 티켓일시에
잘못된 티켓화면 필요

**Comment by 9yujin** [comment]
![스크린샷 2022-08-13 오전 12 13 47](https://user-images.githubusercontent.com/55226431/184385738-a6801914-6603-48e7-8e7e-cf5d4d2719d4.png)

주문목록에서 양일권 구매시 BOTH가 아니라 '양일권'으로 워딩 수정
ticketing용 컴포넌트에서 만들어둔 로직 있으니까 참고 
YB OB도 날짜로
이거도 티켓팅에 코드 있어

@wjdtkdgns

**Comment by 9yujin** [comment]
`ticket` 쿼리 캐시된 상태에서 더 예매할래요로 예매하고 돌아왔을때 예매한 티켓 갱신하기!!!

@9yujin

**Comment by 9yujin** [comment]
인증하고나서 뒤로가기 눌렀을때 인증페이지 다시 접근 못하도록

@9yujin

**Comment by ImNM** [comment]
https://user-images.githubusercontent.com/13329304/184429321-9bf3b0af-4dd7-4d71-8c91-b6c1d2c42ec0.MOV



인증 후 뒤로가기눌렀을 때 또 인증페이지나오는부분

**Comment by ImNM** [comment]
주문 페이지에서 
상단 뒤로가기 워딩이 마이페이지로 

상단 뒤로가기 워딩 수정

**Comment by ImNM** [comment]
댓글을 단후에 전체갯수 +1 증가안함
추가되었으면하는기능 
스크롤이 맨밑으로 내려간상태에서 댓글 달면 스크롤을 맨위로 올렸음 좋겠음

**Comment by ImNM** [comment]
배너에  입금 까먹었을때? 입금정보 다시보여주는 부분 없음... 없어진건감?
넣어야됨

**Comment by ImNM** [comment]
![57FD6A60-A57E-4C0B-8F67-77B952B13391](https://user-images.githubusercontent.com/13329304/184430268-f7a0fd7e-e40c-428b-a657-d40516559a05.png)


https://user-images.githubusercontent.com/13329304/184430661-b66deb9b-526d-4dc1-8762-aa3ec97145cf.MOV


로그인이 되어있는 (인증이 되어있는 상태에서)
문자메시지로온 링크로 들어가면 

마이페이지로가기버튼이 동작을 안함
 히스토리기반인가? 마이페이지로 강제로 푸시해야할둣

**Comment by ImNM** [comment]
![F1C3C63F-1E75-4884-8555-9488365C2B3D](https://user-images.githubusercontent.com/13329304/184431108-688286d5-29b3-45f4-aa96-528b815ebba7.png)


바로위 코멘트랑도 마찬가지
mypage로 강제로 url 로접근했을때
Hoc에의해서 인증페이지로 오는건 좋았는데
히스토리가 없는상태여서 뒤로가기 클릭시에
아무데로도 안가짐
홈으로 가기등으로 바꾸면좋을듯

**Comment by 9yujin** [comment]
![image](https://user-images.githubusercontent.com/55226431/184435142-48d1ac09-9a16-49cf-9010-1b4d69d8b529.png)

또 예매할래요 오른쪽에도 마진 들어가기

**Comment by ImNM** [comment]
홈페이제이셔 예매하러가기 버튼 안눌림

**Comment by kim-wonjin** [comment]
![image](https://user-images.githubusercontent.com/80401705/184541436-b5276aad-87be-4c3b-b02f-e86d92ae0b54.png)
모바일 화면 사진 길쭉길쭉

**Comment by gengminy** [comment]
![image](https://user-images.githubusercontent.com/72291860/184541648-02ba8be2-3990-4143-918d-9f33e9a24722.png)

응원톡 텍스트 띄어쓰기 없을 때 overflow-x 처리 안됨

**Comment by kim-wonjin** [comment]
푸터 링크 연결 안됨
고스락 글씨 눌렀을때는  깃허브로 가네용

**Comment by ImNM** [comment]
로그인 안된상황

랜딩페이지 -> 응원 톡보기 버튼 클릭 - > 인증과정 -> 마이페이지 버튼 클릭시 
다시 인증과정으로 넘어감
마이페이지 로 넘어가야함

**Comment by wjdtkdgns** [comment]
> 
> 배너에 입금 까먹었을때? 입금정보 다시보여주는 부분 없음... 없어진건감?

@wjdtkdgns

**Comment by wjdtkdgns** [comment]
> ![D89EC82D-8591-4F14-995C-7E289C15CC1F](https://user-images.githubusercontent.com/13329304/184429798-38a1b768-23f4-45f5-92ae-3d20ab77b87f.png)
> 
> 배너에 입금 까먹었을때? 입금정보 다시보여주는 부분 없음... 없어진건감?

@wjdtkdgns

**Comment by kongnayeon** [comment]
응원톡 전송 눌렀다가 엑스 하면 썼던 내용 안 날아가고 수정할 수 있었으면 좋겠어용...!

**Comment by wjdtkdgns** [comment]
티켓팅 select 페이지에서 check 페이지로 넘어왔을 때, 'react-dom.development.js:86 Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>.' 이런 에러 뜸

**Comment by wjdtkdgns** [comment]
주문목록 페이지 티켓 정보가 업데이트되지 않음

**Comment by 9yujin** [comment]
![image](https://user-images.githubusercontent.com/55226431/184549069-17c4920d-8085-4141-8eb1-58b9d08d333a.jpeg)

- 여기 마진 없음
- 저기 폰트 색상 한단계 진한 검정색으로
- 지도 부분 모바일일때 글씨크기 애매함

**Comment by wjdtkdgns** [comment]
또 예매할래요 컴포넌트 오른쪽 마진 없음 (사파리)

**Comment by wjdtkdgns** [comment]
사파리 사용자 인증 안됨

**Comment by wjdtkdgns** [comment]
access 또는 register 토큰이 없는 상태에서 auth/*로 접근 가능함.

**Comment by wjdtkdgns** [comment]
auth/init 페이지가 안열림

**Comment by wjdtkdgns** [comment]
<img width="419" alt="스크린샷 2022-08-16 오후 9 13 34" src="https://user-images.githubusercontent.com/67852689/184876808-04585f55-a027-4087-b5aa-f64e072f98a8.png">
버튼 가려짐, 클릭 불가능

**Comment by wjdtkdgns** [comment]
talks 페이지 chevron up, down, 종이비행기 모양 버튼에서 커서 모양이 안변함

**Comment by wjdtkdgns** [comment]
<img width="354" alt="스크린샷 2022-08-16 오후 9 36 30" src="https://user-images.githubusercontent.com/67852689/184881084-971f512a-9ec4-4757-b9db-c97bfdd412a1.png">
계좌 복사 버튼 이외의 부분을 눌렀을 경우, 계좌가 복사되지 않음

**Comment by wjdtkdgns** [comment]
access, register 토큰이 모두 없는 상태에서 auth/login/2, auth/init에 접근 가능함

**Comment by wjdtkdgns** [comment]
<img width="205" alt="스크린샷 2022-08-16 오후 9 51 58" src="https://user-images.githubusercontent.com/67852689/184884042-9d380049-fdb8-4f3b-8618-7dbc053faf1d.png">
사파리에서 이렇게 보임

**Comment by wjdtkdgns** [comment]
auth/login/1에서 홈으로 누르거나, 로그인이 만료되었어요 모달에서 '확인했어요' 누르면, 프레임 안에서 메인 페이지가 열림

**Comment by wjdtkdgns** [comment]
티켓 주문 목록 페이지 생성된 주문이 없을 때 스크롤 생김

**Comment by wjdtkdgns** [comment]
404 페이지 스크롤 생김

**Comment by wjdtkdgns** [comment]
티켓팅 Select 페이지 뒤로가기 사라짐

**Comment by wjdtkdgns** [comment]
공연장 위치보기 day 1만 2개 있음. Day 2 없음
